export const countryList = [
  { countryName: "Andorra	", countryCode: "AD" },
  { countryName: "Argentina	", countryCode: "AR" },
  { countryName: "American Samoa	", countryCode: "AS" },
  { countryName: "Austria	", countryCode: "AT" },
  { countryName: "Australia	", countryCode: "AU" },
  { countryName: "Bangladesh	", countryCode: "BD" },
  { countryName: "Belgium	", countryCode: "BE" },
  { countryName: "Bulgaria	", countryCode: "BG" },
  { countryName: "Brazil	", countryCode: "BR" },
  { countryName: "Canada	", countryCode: "CA" },
  { countryName: "Switzerland	", countryCode: "CH" },
  { countryName: "Czech Republic	", countryCode: "CZ" },
  { countryName: "Germany	", countryCode: "DE" },
  { countryName: "Denmark	", countryCode: "DK" },
  { countryName: "Dominican Republic	", countryCode: "DO" },
  { countryName: "Spain	", countryCode: "ES" },
  { countryName: "Finland	", countryCode: "FI" },
  { countryName: "Faroe Islands	", countryCode: "FO" },
  { countryName: "France	", countryCode: "FR" },
  { countryName: "Great Britain	", countryCode: "GB" },
  { countryName: "French Guyana	", countryCode: "GF" },
  { countryName: "Guernsey	", countryCode: "GG" },
  { countryName: "Greenland	", countryCode: "GL" },
  { countryName: "Guadeloupe	", countryCode: "GP" },
  { countryName: "Guatemala	", countryCode: "GT" },
  { countryName: "Guam	", countryCode: "GU" },
  { countryName: "Guyana	", countryCode: "GY" },
  { countryName: "Croatia	", countryCode: "HR" },
  { countryName: "Hungary	", countryCode: "HU" },
  { countryName: "Isle of Man	", countryCode: "IM" },
  { countryName: "India	", countryCode: "IN" },
  { countryName: "Iceland	", countryCode: "IS" },
  { countryName: "Italy	", countryCode: "IT" },
  { countryName: "Jersey	", countryCode: "JE" },
  { countryName: "Japan	", countryCode: "JP" },
  { countryName: "Liechtenstein	", countryCode: "LI" },
  { countryName: "Sri Lanka	", countryCode: "LK" },
  { countryName: "Lithuania	", countryCode: "LT" },
  { countryName: "Luxembourg	", countryCode: "LU" },
  { countryName: "Monaco	", countryCode: "MC" },
  { countryName: "Moldavia	", countryCode: "MD" },
  { countryName: "Marshall Islands	", countryCode: "MH" },
  { countryName: "Macedonia	", countryCode: "MK" },
  { countryName: "Northern Mariana Islands	", countryCode: "MP" },
  { countryName: "Martinique	", countryCode: "MQ" },
  { countryName: "Mexico	", countryCode: "MX" },
  { countryName: "Malaysia	", countryCode: "MY" },
  { countryName: "Holland	", countryCode: "NL" },
  { countryName: "Norway	", countryCode: "NO" },
  { countryName: "New Zealand	", countryCode: "NZ" },
  { countryName: "Phillippines	", countryCode: "PH" },
  { countryName: "Pakistan	", countryCode: "PK" },
  { countryName: "Poland	", countryCode: "PL" },
  { countryName: "Saint Pierre and Miquelon	", countryCode: "PM" },
  { countryName: "Puerto Rico	", countryCode: "PR" },
  { countryName: "Portugal	", countryCode: "PT" },
  { countryName: "French Reunion	", countryCode: "RE" },
  { countryName: "Russia	", countryCode: "RU" },
  { countryName: "Sweden	", countryCode: "SE" },
  { countryName: "Slovenia	", countryCode: "SI" },
  { countryName: "Svalbard & Jan Mayen Islands	", countryCode: "SJ" },
  { countryName: "Slovak Republic	", countryCode: "SK" },
  { countryName: "San Marino	", countryCode: "SM" },
  { countryName: "Thailand	", countryCode: "TH" },
  { countryName: "Turkey	", countryCode: "TR" },
  { countryName: "United States	", countryCode: "US" },
  { countryName: "Vatican	", countryCode: "VA" },
  { countryName: "Virgin Islands	", countryCode: "VI" },
  { countryName: "Mayotte	", countryCode: "YT" },
  { countryName: "South Africa	", countryCode: "ZA" },
];
